---
language: ruby
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script: "bundle exec rake test SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 3.8.1"
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 4.0.0"
  - rvm: 2.3.3
    env: PUPPET_VERSION="~> 4.0" CHECK=rubocop
notifications:
  email: dejan@golja.org
