sudo: required

# Use Travis' Ubuntu Trusty machines. They have more RAM.
# It does not affect which OSs we are testing, since they all provided
# by Docker containers. This simply defines which OS Docker itself will
# be running on.
dist: trusty

services:
  - docker

language: ruby

rvm:
  - 2.2.5

script:
  # Some of our tests can take long time, and not output anything while they
  # are running. If this goes on for too long (ten minutes), then Travis
  # will assume the build has stalled, and kill it.
  #
  # It's a bit cheeky, but let's make sure that _something_ goes to STDOUT
  # every five minutes, so that our build won't be killed unjustly.
  - (while true; do date --iso-8601=seconds; sleep 300; done) &
  - (if [[ -n $TRAVIS_TEST_UNIT ]]; then make test-unit; else bundle exec rake beaker; fi)

env:
  global:
    - TRAVIS_CI=true
    - LOGSTASH_VERSION=5.0.1
    - BEAKER_PE_DIR=spec/fixtures/artifacts
  matrix:
    # Run the unit tests once.
    # FIXME: ...actually don't for now. They are a mess.
    # FIXME: - TRAVIS_TEST_UNIT=true

    # Then run the acceptance tests across the matrix.
    - PUPPET_VERSION=3.8.7 BEAKER_set=centos-6
    - PUPPET_VERSION=4.8.1 BEAKER_set=centos-6
    - PUPPET_VERSION=3.8.4 BEAKER_set=centos-6 BEAKER_PE_VER=3.8.4 BEAKER_IS_PE=true

    - PUPPET_VERSION=3.8.7 BEAKER_set=centos-7
    - PUPPET_VERSION=4.0.0 BEAKER_set=centos-7
    - PUPPET_VERSION=4.1.0 BEAKER_set=centos-7
    - PUPPET_VERSION=4.2.3 BEAKER_set=centos-7
    - PUPPET_VERSION=4.3.2 BEAKER_set=centos-7
    - PUPPET_VERSION=4.8.1 BEAKER_set=centos-7

    - PUPPET_VERSION=3.8.7 BEAKER_set=debian-7
    - PUPPET_VERSION=4.8.1 BEAKER_set=debian-7
    # FIXME: Beaker fails to install PE on Debian 7.
    # Example: https://travis-ci.org/elastic/puppet-logstash/jobs/159507699#L542
    # - PUPPET_VERSION=3.8.4 BEAKER_set=debian-7 BEAKER_PE_VER=3.8.4 BEAKER_IS_PE=true

    - PUPPET_VERSION=3.8.7 BEAKER_set=debian-8
    - PUPPET_VERSION=4.8.1 BEAKER_set=debian-8

    - PUPPET_VERSION=3.8.7 BEAKER_set=opensuse-13

    - PUPPET_VERSION=3.8.7 BEAKER_set=ubuntu-1204
    - PUPPET_VERSION=4.8.1 BEAKER_set=ubuntu-1204

    - PUPPET_VERSION=3.8.7 BEAKER_set=ubuntu-1404
    - PUPPET_VERSION=4.8.1 BEAKER_set=ubuntu-1404

    - PUPPET_VERSION=3.8.7 BEAKER_set=ubuntu-1604
    - PUPPET_VERSION=4.8.1 BEAKER_set=ubuntu-1604
