language: ruby

rvm:
  - 1.9.3
  - 2.1.0

env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.6.2"

before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version

script: "rake"

gemfile: Gemfile

matrix:
  allow_failures:
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 2.7.0"
  exclude:
    - rvm: 2.1.0
      env: PUPPET_VERSION="~> 2.7.0"
